### ISSUE TITLE
SPI download fail in log

### ISSUE THREAD

**Issue by ggee** [DCC-EX/exInstaller#19]
In the installer log pane, there is an error for failed download of SPI.

```
Failed to download library by name due to Status(StatusCode="Unknown", Detail="looking for library: library SPI not found") attempting to obtain via git
Obtaining https://github.com/arduino-libraries/Ethernet via git

```

I also noticed the URL does not end in .git.

**Comment by dexslab** [comment]
This issue I need to figure out and get a proper link but it should already be included in avr platform download

**Comment by dexslab** [comment]
Bug has been fixed in latest dev push

**Comment by peteGSX** [comment]
Closing in favour of the new EX-Installer.
