### ISSUE TITLE
arduino-cli remains running after installer closed

### ISSUE THREAD

**Issue by ggee** [DCC-EX/exInstaller#20]
After closing the installer, there is an arduino-cli process left running.   The reason I consider this an issue is that I can't delete the folder because the process is still running.  This would be very confusing to people that didn't know this was running and would not know what to look for.

Instead of starting arduino-cli when the installer starts, which can cause a crash if someone clicks a button  (#10).  Maybe arduino-cli should be started when you click the compile button and exit when the compile completes.  Yes, this may make the compile process take a few seconds longer, but that is only an issue for people like us that run it over and over.  This could also solve #10 possibly. 

win-x64 installer.

**Comment by dexslab** [comment]
I will look into it just there is a lot of things needed with the cli grpc to work properly it runs as a daemon but it's also set to shutdown on the app closing but for some reason it doesn't work 100% of the time.

**Comment by peteGSX** [comment]
Closing in favour of the new EX-Installer.
