### ISSUE TITLE
win64 zip package contains nested folders

### ISSUE THREAD

**Issue by ggee** [DCC-EX/exInstaller#21]
When unzipping the x64 package, the installer is located deep inside the zip file.  The zip file contains a folder structure BaseStationInstaller\bin\Release\netcoreapp3.1\win-x64\publish before the binaries can be found.

**Comment by GunflintAndDeadRiverRR** [comment]
Great call on this. For many/most newbie users, it would be hard for them to drill down to the executable.

**Comment by peteGSX** [comment]
Closing in favour of the new EX-Installer.
