### ISSUE TITLE
exInstaller-linux-x64.zip issues

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/exInstaller#27]
- There is no file with the x (Executable) bit set in the exInstaller-linux-x64.zip
- It does not unzip into a subfolder
- can not select anything in the drop down menues 
- can not select checkboxes
- Odd layout

If any of the above is because no Arduino was found it should say so
Actually the big black area to the right and bottom of the screen is transparent.  It looks like the window is big, but the graphics don't stretch so it only takes up part of the window.

**Comment by peteGSX** [comment]
Closing in favour of the new EX-Installer.
