### ISSUE TITLE
Bug Report: Installer fails on Linux

### ISSUE THREAD

**Issue by pmantoine** [DCC-EX/exInstaller#31]
### EX-Installer Version

Latest

### Operating System

Linux

### Operating System Version

Debian

### Bug description

When I run exInstaller it executes but then tries to run port scanner and fails as the file doesn’t exist. Is there a problem with the tar file being incomplete?

The site downloads exInstaller-linux-x64.tar.gz

The file the exInstaller is looking for is ../1.2.1/serial-discovery. this file doesn’t exist in the tar either.

### Steps to reproduce the bug

Execute exInstaller... fails unable to find the port scanner, ../1.2.1./serial-discovery

### Expected behaviour

Should build a list of serial ports for the exInstaller port selector.

### Additional context

Discovered by user garethw on Discord, 22-Sep-2022, mentioned in #general chat channel.

**Comment by dexslab** [comment]
Have you tried the new version posted on our Discord yet.

**Comment by prchal** [comment]
See issue #26 - delete folders tools and packages

**Comment by peteGSX** [comment]
The new incoming EX-Installer will address this.
