### ISSUE TITLE
[Documentation Update]: Explain how networking options work

### ISSUE THREAD

**Issue by FrightRisk** [DCC-EX/exInstaller#34]
### Documentation details

1. What happens if you don't do anything? The CS should default to AP mode with DCC-EXxxxxxx and PASSxxxxxx for credentials but the instructions say that you MUST check the box if you want WiFi. So the installer works differently than using the IDE? 
2. Better document how to use the SSID/password, channel, don't touch options.

**Comment by pmantoine** [comment]
Also add documentation of ability to change the SSID in AP mode for folks running multiple CS at a time, such as clubs and exhibitions etc.??

**Comment by peteGSX** [comment]
New incoming EX-Installer, if this crops up then will address then.
