### ISSUE TITLE
Ex-Installer will not download

### ISSUE THREAD

**Issue by helipilot50** [DCC-EX/exInstaller#36]
### EX-Installer Version

latest

### Operating System

MacOS

### Operating System Version

macOS Ventura version 13.3.1

### Bug description

Cannot down load EX-Installer

Dialog box saying "OS Version not supported at this time

### Steps to reproduce the bug

Navigate to https://dcc-ex.com/download/ex-commandstation.html
Click the button "Automated Installer"

### Expected behaviour

download

### Screenshots

<img width="971" alt="dcc-EX installer error" src="https://user-images.githubusercontent.com/2374962/232207690-c2c749ea-a4d1-4fa7-9a05-3914c4c671ce.png">

**Comment by habazut** [comment]
Om MacOS you need today go the Arduino IDE install route. Unclear if we get an integrated installer to work as MacOS will prevent this and that all in the name of protecting the user from the world.

Harald.

**Comment by peteGSX** [comment]
The incoming EX-Installer is intended to address this.
