### ISSUE TITLE
[Support Request]: Cannot run installer on Ubuntu 22.10

### ISSUE THREAD

**Issue by skyecas** [DCC-EX/exInstaller#37]
### Version

Beta 2.4.0

### Operating System

Linux

### Operating System Version

Kinetic (22.10)

### Issue description

Attempting to follow the installation instructions, get to running the installation step and hit a failure:

```bash
$ ./exInstaller
No usable version of libssl was found
Aborted (core dumped)
```

libssl is most up to date, does exInstaller expect an older version?
```bash
$ sudo apt install libssl-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libssl-dev is already the newest version (3.0.5-2ubuntu2.3).
```

**Comment by peteGSX** [comment]
Hi there @SK1Y101 , the installer is known to have major issues in Linux environments at the moment, so for now we recommend using the Arduino IDE as outlined on our website [here](https://dcc-ex.com/ex-commandstation/advanced-setup/installation-options/arduino-ide.html).

We are working on a replacement installer but that's probably going to be a few weeks away yet.

If you need further help I'd recommend reaching out via our [Discord server](https://discord.gg/PuPnNMp8Qf) also.

**Comment by skyecas** [comment]
Awesome, thanks. I'll do that instead!

**Comment by habazut** [comment]
I think you might be able to test the new installer even if it is not done yet
```
sudo apt install python3.8-venv    #bootstrap virtual env
sudo apt install python3.8-tk         #can not be installed via pip
python -m venv ~/pvenv
source ~/pvenv/bin/activate
git clone https://github.com/DCC-EX/EX-Installer
pip install -r EX-Installer/requirements.txt
cd EX-Installer
python3 -m ex_installer
```
Have fun.
Harald.
